name: Flight Software Bazel-based HOOTL Tests

on:
  pull_request:
    branches: [ master ]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        sudo apt-get install bazel

    - name: Build Software
      run: |
        bazel build //src/fsw:hootl_leader
        bazel build //src/fsw:hootl_follower
        bazel build //src/fsw:hootl_realtime_leader
        bazel build //src/fsw:hootl_realtime_follower
        bazel test //test:desktop
