name: Flight Software HOOTL Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'tlm/**'
      - 'tools/**'
      - 'cmdclient/**'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - 'ptest/README.md'

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - uses: bazelbuild/setup-bazelisk@v1
    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        key: bazel

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        platformio update

    - name: Install Psim
      run: |
        pip install -e lib/common/psim

    - name: CI Checkout Case and Empty case
      run: |
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t CICase
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t EmptyCase
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t EmptySimCase
        !(python -m ptest runsim -c ptest/configs/hootl_speedup.json -t FailingEmptyCase)
        !(python -m ptest runsim -c ptest/configs/hootl_speedup.json -t FailingEmptySimCase)
        python -m ptest runsim -c ptest/configs/hootl.json -t AttitudeNoSunVectorsInitializationCase

    - name: Mission Rehearsal Cases
      run: |
        python -m ptest runsim -c ptest/configs/hootl_hootl.json -t DualSatDetumbleCase 
        python -m ptest runsim -c ptest/configs/hootl_hootl.json -t DualSatFarFieldCase 
        python -m ptest runsim -c ptest/configs/hootl_hootl.json -t DualSatNearFieldCase 
        python -m ptest runsim -c ptest/configs/hootl_hootl.json -t DualSatStandbyCase 
        python -m ptest runsim -c ptest/configs/hootl_hootl.json -t DualSatStartupCase 
        python -m ptest runsim -c ptest/configs/hootl.json -t SingleSatDetumbleCase 
        python -m ptest runsim -c ptest/configs/hootl.json -t SingleSatStandbyCase 
        python -m ptest runsim -c ptest/configs/hootl.json -t SingleSatStartupCase 

    - name: Hardware Checkout Cases
      run: |
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t DCDCCheckoutCase 
        python -m ptest runsim -c ptest/configs/hootl.json -t GomspaceCheckoutCase 
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t SpinMotorsCase 
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t ADCSCheckoutCase 
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t PiksiCheckoutCase 
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t PropStateMachineCase 

    - name: Fault Handling Cases
      run: |
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t ADCSWheelFaultHandler 
        python -m ptest runsim -c ptest/configs/hootl.json -t AttitudeFaultHandlerCase 
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t LowBattFaultHandler 
        python -m ptest runsim -c ptest/configs/hootl.json -t PropFaultHandler 
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t QuakePowerCycling 
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t PiksiFaultHandler 
        python -m ptest runsim -c ptest/configs/hootl_hootl_speedup.json -t PiksiFaultNearField
        python -m ptest runsim -c ptest/configs/hootl_hootl_speedup.json -t PiksiFaultNearField2 

    # Add quake and piksi fault handler to the above once completed.
    - name: Mission Checkout Cases
      run: |
        python -m ptest runsim -c ptest/configs/hootl_speedup.json -t DeploymentToInitHold 
